// cars-data.js
// Full inventory extracted from Sephoc Motors' cars.co.ug listing PDFs (pages 17-27).
// price is in UGX (whole shillings). null price means source PDF had no clear price - DO NOT invent one, confirm with client.
// image is a placeholder path until real photos are matched in (see photo-matching notes).
// isLatestArrival flags the 10 cars featured on the homepage, in the client-approved order.
const CARS_DATA = [
  {
    id: 90,
    brand: "Ford",
    model: "Ford Everest",
    year: 2024,
    price: null,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: true,
    latestArrivalOrder: 1,
    verifyNote: "SALE - price not listed on source, confirm with client"
  },
  {
    id: 91,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz GLS 400d 4MATIC",
    year: 2023,
    price: null,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: true,
    latestArrivalOrder: 2,
    verifyNote: "Source showed 122.32k - likely data-entry glitch, DO NOT publish price without client confirmation"
  },
  {
    id: 92,
    brand: "Toyota",
    model: "Toyota Mark X Premium",
    year: 2013,
    price: null,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: "SALE - price not listed on source"
  },
  {
    id: 101,
    brand: "Jeep",
    model: "Jeep Wrangler",
    year: 2020,
    price: 133360000,
    mileageKm: 54000,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: true,
    latestArrivalOrder: 5,
    verifyNote: null
  },
  {
    id: 102,
    brand: "Toyota",
    model: "Toyota RAV4",
    year: 2020,
    price: 132000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: true,
    latestArrivalOrder: 6,
    verifyNote: null
  },
  {
    id: 103,
    brand: "Jeep",
    model: "Jeep",
    year: 2017,
    price: 132000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 104,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz ML350 4MATIC",
    year: 2013,
    price: 130000000,
    mileageKm: 76420,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 105,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz GLS",
    year: 2017,
    price: 130000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 106,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2019,
    price: 130000000,
    mileageKm: 8600,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 107,
    brand: "Toyota",
    model: "Toyota Hilux Double Cab",
    year: 2017,
    price: 130000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 108,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz ML",
    year: 2013,
    price: 128000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 109,
    brand: "Toyota",
    model: "Toyota Land Cruiser Prado",
    year: 2010,
    price: 128000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 110,
    brand: "Toyota",
    model: "Toyota Land Cruiser Prado",
    year: 2015,
    price: 128000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 111,
    brand: "Nissan",
    model: "Nissan Navara",
    year: 2016,
    price: 127000000,
    mileageKm: null,
    transmission: "Manual",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 112,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz ML3xx",
    year: 2014,
    price: 125000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: true,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 113,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz E400",
    year: 2017,
    price: 123000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 114,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz C200",
    year: 2019,
    price: 120000000,
    mileageKm: 41000,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: true,
    latestArrivalOrder: 8,
    verifyNote: null
  },
  {
    id: 115,
    brand: "Volvo",
    model: "Volvo XC60 D4",
    year: 2018,
    price: 120000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: true,
    latestArrivalOrder: 9,
    verifyNote: null
  },
  {
    id: 116,
    brand: "Toyota",
    model: "Toyota Hilux SR5",
    year: 2017,
    price: 118000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 117,
    brand: "Toyota",
    model: "Toyota Land Cruiser Prado",
    year: 2021,
    price: 118000000,
    mileageKm: null,
    transmission: "Manual",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: true,
    latestArrivalOrder: 4,
    verifyNote: null
  },
  {
    id: 118,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2017,
    price: 100000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 119,
    brand: "Toyota",
    model: "Toyota Alphard",
    year: 2016,
    price: 99000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 120,
    brand: "Toyota",
    model: "Toyota Alphard",
    year: 2015,
    price: 99000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 121,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz ML400",
    year: 2015,
    price: 98000000,
    mileageKm: 83601,
    transmission: "Manual",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 122,
    brand: "Mazda",
    model: "Mazda CX-50",
    year: 2019,
    price: 98000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 123,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz ML",
    year: 2013,
    price: 98000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 124,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz ML",
    year: 2012,
    price: 98000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 125,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz ML",
    year: 2014,
    price: 98000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 126,
    brand: "Subaru",
    model: "Subaru Forester",
    year: 2018,
    price: 98000000,
    mileageKm: 72000,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 127,
    brand: "Peugeot",
    model: "Peugeot 3008",
    year: 2018,
    price: 98000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 128,
    brand: "Subaru",
    model: "Subaru Forester",
    year: 2019,
    price: 96000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 129,
    brand: "Subaru",
    model: "Subaru Forester X",
    year: 2020,
    price: 96000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 130,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2018,
    price: 95000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 131,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2017,
    price: 95000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 132,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2017,
    price: 95000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 133,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2018,
    price: 95170000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 134,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2018,
    price: 95170000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 135,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2018,
    price: 95170000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 136,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz ML350",
    year: 2014,
    price: 94000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: true,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 137,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz ML350",
    year: 2012,
    price: 92000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 138,
    brand: "Subaru",
    model: "Subaru Forester",
    year: 2019,
    price: 90000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 139,
    brand: "Toyota",
    model: "Toyota Harrier Hybrid",
    year: 2017,
    price: 90000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Hybrid",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 140,
    brand: "Toyota",
    model: "Toyota Harrier Anaconda",
    year: 2016,
    price: 90000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 141,
    brand: "Subaru",
    model: "Subaru Forester X",
    year: 2019,
    price: 90000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 142,
    brand: "Subaru",
    model: "Subaru Forester X",
    year: 2019,
    price: 90000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 143,
    brand: "Volvo",
    model: "Volvo S90 T5",
    year: 2022,
    price: 87000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: true,
    latestArrivalOrder: 3,
    verifyNote: null
  },
  {
    id: 144,
    brand: "Subaru",
    model: "Subaru Forester",
    year: 2018,
    price: 86000000,
    mileageKm: null,
    transmission: "Other",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 145,
    brand: "Subaru",
    model: "Subaru Forester X Break",
    year: 2018,
    price: 86000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 146,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2018,
    price: 85000000,
    mileageKm: 83601,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 147,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2016,
    price: 85000000,
    mileageKm: 67000,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 148,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2016,
    price: 85000000,
    mileageKm: 83222,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 149,
    brand: "Mazda",
    model: "Mazda CX-50",
    year: 2018,
    price: 85000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 150,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2017,
    price: 85000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 151,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2017,
    price: 85000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 152,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2017,
    price: 85000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 153,
    brand: "Mitsubishi",
    model: "Mitsubishi Pajero Sport",
    year: 2017,
    price: 85000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 154,
    brand: "Toyota",
    model: "Toyota Alphard",
    year: 2015,
    price: 85000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 155,
    brand: "Subaru",
    model: "Subaru Forester X",
    year: 2018,
    price: 85000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 156,
    brand: "Mazda",
    model: "Mazda CX-8",
    year: 2018,
    price: 85000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 157,
    brand: "Subaru",
    model: "Subaru Forester",
    year: 2018,
    price: 85000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 158,
    brand: "Subaru",
    model: "Subaru Forester X Break",
    year: 2018,
    price: 85000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 159,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2017,
    price: 85150000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 160,
    brand: "Jaguar",
    model: "Jaguar XF",
    year: 2019,
    price: 83000000,
    mileageKm: 101407,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: true,
    latestArrivalOrder: 7,
    verifyNote: null
  },
  {
    id: 161,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz C180",
    year: 2016,
    price: 82000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 162,
    brand: "Mazda",
    model: "Mazda CX-50",
    year: 2017,
    price: 79000000,
    mileageKm: 89000,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 163,
    brand: "BMW",
    model: "BMW X1",
    year: 2018,
    price: 78000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: true,
    latestArrivalOrder: 10,
    verifyNote: null
  },
  {
    id: 164,
    brand: "Mazda",
    model: "Mazda CX-50",
    year: 2017,
    price: 78000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 165,
    brand: "Volkswagen",
    model: "Volkswagen Tiguan",
    year: 2016,
    price: 77000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 166,
    brand: "Mazda",
    model: "Mazda CX-5",
    year: 2018,
    price: 76000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 167,
    brand: "Mazda",
    model: "Mazda CX-5",
    year: 2017,
    price: 76000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 168,
    brand: "Toyota",
    model: "Toyota C-HR",
    year: 2017,
    price: 75000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 169,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2015,
    price: 75000000,
    mileageKm: 42703,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 170,
    brand: "Toyota",
    model: "Toyota Harrier GS",
    year: 2015,
    price: 75000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 171,
    brand: "Audi",
    model: "Audi Q3",
    year: 2017,
    price: 75000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 172,
    brand: "Mazda",
    model: "Mazda CX-5",
    year: 2017,
    price: 75000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 173,
    brand: "Mazda",
    model: "Mazda CX-50",
    year: 2017,
    price: 75000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 174,
    brand: "Mazda",
    model: "Mazda CX-5",
    year: 2017,
    price: 75000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 175,
    brand: "Toyota",
    model: "Toyota Hiace Super GL",
    year: 2011,
    price: 75000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 176,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2012,
    price: 68000000,
    mileageKm: 59000,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 177,
    brand: "Mitsubishi",
    model: "Mitsubishi",
    year: 2017,
    price: 68000000,
    mileageKm: 53152,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 178,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2014,
    price: 68000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 179,
    brand: "Mazda",
    model: "Mazda CX-5",
    year: 2017,
    price: 68000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 180,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz GLE",
    year: 2014,
    price: 68000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 181,
    brand: "Mazda",
    model: "Mazda CX-50",
    year: 2017,
    price: 68000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Diesel",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 182,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2016,
    price: 66500000,
    mileageKm: 81460,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 183,
    brand: "Subaru",
    model: "Subaru Forester X",
    year: 2017,
    price: 65000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 184,
    brand: "Toyota",
    model: "Toyota RAV4",
    year: 2018,
    price: 65000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 185,
    brand: "Subaru",
    model: "Subaru Forester",
    year: 2018,
    price: 64980000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 186,
    brand: "Toyota",
    model: "Toyota Alphard",
    year: 2014,
    price: 60000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 187,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2012,
    price: 59000000,
    mileageKm: 53000,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 188,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2010,
    price: 58000000,
    mileageKm: 25000,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 189,
    brand: "BMW",
    model: "BMW 3 Series GT",
    year: 2013,
    price: 58000000,
    mileageKm: 71453,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 190,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2012,
    price: 58000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 191,
    brand: "Subaru",
    model: "Subaru Forester",
    year: 2017,
    price: 58000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 192,
    brand: "Subaru",
    model: "Subaru XV",
    year: 2017,
    price: 58000000,
    mileageKm: 34175,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 193,
    brand: "Subaru",
    model: "Subaru XT",
    year: 2015,
    price: 58000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 194,
    brand: "Subaru",
    model: "Subaru Forester",
    year: 2017,
    price: 57000000,
    mileageKm: null,
    transmission: "Manual",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 195,
    brand: "Toyota",
    model: "Toyota Noah",
    year: 2014,
    price: 56000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 196,
    brand: "Subaru",
    model: "Subaru XV STI",
    year: 2017,
    price: 55000000,
    mileageKm: null,
    transmission: "Other",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 197,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz E300",
    year: 2010,
    price: 55000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 198,
    brand: "Subaru",
    model: "Subaru Forester",
    year: 2016,
    price: 55000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 199,
    brand: "Volkswagen",
    model: "Volkswagen Golf GT R-Line",
    year: 2012,
    price: 55000000,
    mileageKm: 51143,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 200,
    brand: "Toyota",
    model: "Toyota Alphard",
    year: 2011,
    price: 55000000,
    mileageKm: 51085,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 201,
    brand: "Toyota",
    model: "Toyota Fortuner",
    year: 2007,
    price: 55000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 202,
    brand: "Toyota",
    model: "Toyota Noah",
    year: 2015,
    price: 53000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 203,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2010,
    price: 50000000,
    mileageKm: 80296,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 204,
    brand: "Toyota",
    model: "Toyota Harrier",
    year: 2012,
    price: 50000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 205,
    brand: "Toyota",
    model: "Toyota Mark X Premium",
    year: 2013,
    price: 50000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 206,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz B180",
    year: 2014,
    price: 49000000,
    mileageKm: 56321,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 207,
    brand: "Subaru",
    model: "Subaru Legacy B4",
    year: 2016,
    price: 48000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 208,
    brand: "Toyota",
    model: "Toyota Mark X",
    year: 2013,
    price: 48000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 209,
    brand: "Toyota",
    model: "Toyota Mark X",
    year: 2010,
    price: 47000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 210,
    brand: "Subaru",
    model: "Subaru Legacy",
    year: 2017,
    price: 45000000,
    mileageKm: 66000,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 211,
    brand: "Toyota",
    model: "Toyota Noah SI",
    year: 2011,
    price: 45000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 212,
    brand: "Toyota",
    model: "Toyota Succeed",
    year: 2019,
    price: 45000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 213,
    brand: "Subaru",
    model: "Subaru Impreza",
    year: 2014,
    price: 45000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 214,
    brand: "BMW",
    model: "BMW X1",
    year: 2014,
    price: 45000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 215,
    brand: "Subaru",
    model: "Subaru B4",
    year: 2015,
    price: 45000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 216,
    brand: "Subaru",
    model: "Subaru Legacy B4",
    year: 2015,
    price: 45000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 217,
    brand: "Toyota",
    model: "Toyota Noah",
    year: 2013,
    price: 45000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 218,
    brand: "Subaru",
    model: "Subaru Forester",
    year: 2013,
    price: 45000000,
    mileageKm: 116000,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 219,
    brand: "Subaru",
    model: "Subaru Impreza GT",
    year: 2017,
    price: 44000000,
    mileageKm: 54263,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 220,
    brand: "Toyota",
    model: "Toyota Noah SI Grade",
    year: 2011,
    price: 44000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 221,
    brand: "Volkswagen",
    model: "Volkswagen Tiguan",
    year: 2010,
    price: 44000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 222,
    brand: "Subaru",
    model: "Subaru Forester",
    year: 2011,
    price: 43000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 223,
    brand: "Toyota",
    model: "Toyota Noah SI",
    year: 2012,
    price: 42000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 224,
    brand: "Mini",
    model: "Mini Cooper Crossover",
    year: 2013,
    price: 42000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 225,
    brand: "Volkswagen",
    model: "Volkswagen Golf",
    year: 2014,
    price: 40000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 226,
    brand: "Volkswagen",
    model: "Volkswagen Tiguan",
    year: 2014,
    price: 39000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 227,
    brand: "Toyota",
    model: "Toyota Vanguard",
    year: 2012,
    price: 38000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 228,
    brand: "Subaru",
    model: "Subaru Legacy B4",
    year: 2013,
    price: 38000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 229,
    brand: "Toyota",
    model: "Toyota Land Cruiser Prado",
    year: 2001,
    price: 38000000,
    mileageKm: 88000,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 230,
    brand: "Toyota",
    model: "Toyota Rumion",
    year: 2012,
    price: 38000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 231,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz E250 Convertible",
    year: 2013,
    price: 38000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 232,
    brand: "Toyota",
    model: "Toyota Fielder",
    year: 2011,
    price: 37000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 233,
    brand: "Toyota",
    model: "Toyota Wish",
    year: 2012,
    price: 36000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 234,
    brand: "Toyota",
    model: "Toyota Wish",
    year: 2011,
    price: 35000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 235,
    brand: "BMW",
    model: "BMW X5",
    year: 2014,
    price: 35000000,
    mileageKm: 180000,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 236,
    brand: "Toyota",
    model: "Toyota Sienta",
    year: 2013,
    price: 35000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 237,
    brand: "Subaru",
    model: "Subaru Impreza",
    year: 2014,
    price: 34000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 238,
    brand: "Toyota",
    model: "Toyota Fielder",
    year: 2010,
    price: 33000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: true,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 239,
    brand: "Mercedes-Benz",
    model: "Mercedes-Benz E200",
    year: 2010,
    price: 32000000,
    mileageKm: 3804,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 240,
    brand: "Toyota",
    model: "Toyota Mark X",
    year: 2015,
    price: 30000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 241,
    brand: "Subaru",
    model: "Subaru Impreza GH",
    year: 2012,
    price: 29000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 242,
    brand: "Subaru",
    model: "Subaru Impreza",
    year: 2013,
    price: 29000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 243,
    brand: "Toyota",
    model: "Toyota Fielder",
    year: 2009,
    price: 27000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 244,
    brand: "Toyota",
    model: "Toyota Rumion",
    year: 2008,
    price: 25500000,
    mileageKm: 83601,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 245,
    brand: "BMW",
    model: "BMW 320i",
    year: 2008,
    price: 25000000,
    mileageKm: null,
    transmission: "Auto",
    fuel: "Petrol",
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
  {
    id: 246,
    brand: "Toyota",
    model: "Toyota Rumion",
    year: 2011,
    price: 24000000,
    mileageKm: 94302,
    transmission: "Auto",
    fuel: null,
    sold: false,
    image: "images/placeholder-car.jpg",
    images: ["images/placeholder-car.jpg"],
    isLatestArrival: false,
    latestArrivalOrder: null,
    verifyNote: null
  },
];

// Helper: get the 10 homepage Latest Arrivals cars in client-approved order
function getLatestArrivals() {
  return CARS_DATA.filter(c => c.isLatestArrival).sort((a,b) => a.latestArrivalOrder - b.latestArrivalOrder);
}

function formatPrice(price) {
  if (price === null || price === undefined) return "Contact us for price";
  return "USh " + (price / 1000000).toLocaleString("en-US", {maximumFractionDigits: 2}) + "M";
}